### PR TITLE
Updating to version 0.8.0

### PR DESCRIPTION
**Pull request by tanema**
### What are you trying to accomplish with this PR?
Updating to the newest release of themekit

### Checklist
For contributors:
- [ ] I have updated the documentation in the [README file](https://github.com/Shopify/node-themekit/blob/master/README.md) to reflect these changes, if applicable.

For maintainers:
- [x] I have :tophat:'d these changes.
- [ ] I have bumped the `package.json` version in a separate PR, if applicable.

Considerations:
- Changes may require updates to the [Slate docs](https://shopify.github.io/slate/) or the [`@shopify/slate-tools`](https://github.com/Shopify/slate/tree/master/packages/slate-tools) package.

### CODE REVIEW

**Comment by macdonaldr93** [comment]
That might have been a can of worms 🤔 ... I'm getting this now:

```
-(node:24205) UnhandledPromiseRejectionWarning: Error: Couldn't execute the `/Users/ryanmacdonald/Shopify/node-themekit/bin/theme` binary. Make sure it has the right permissions.
    at executable.then.works (/Users/ryanmacdonald/Shopify/node-themekit/node_modules/bin-check/index.js:13:11)
(node:24205) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24205) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by tanema** [comment]
Yeah, I cannot figure out how to make the permissions work for that now.

**Comment by tanema** [comment]
Cannot update packages because the bin-wrapper package cannot create an executable anymore https://github.com/kevva/bin-wrapper/issues/67

**Comment by macdonaldr93** [comment]
Sounds great! Feel free to ping me if you want 👀  on that

**Comment by tanema** [comment]
I am just going to close this in favour of the other PR

**Pull request closed without merging**
